name: CI React Node

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Récupérer le code
        uses: actions/checkout@v4

      - name: 2. Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 3. Installer les dépendances
        run: |
          cd frontend
          npm ci

      - name: 4. Lancer ESLint
        run: |
          cd frontend
          npm run lint

      - name: 5. Lancer les tests
        run: |
          cd frontend
          npm test -- --watchAll=false --coverage

      - name: 6. Build React
        run: |
          cd frontend
          npm run build

      - name: 7. Build et push image Docker frontend
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u hub99-h --password-stdin
          docker build -t ghcr.io/hub99-h/tp-ci-frontend:latest ./frontend
          docker push ghcr.io/hub99-h/tp-ci-frontend:latest

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Récupérer le code
        uses: actions/checkout@v4

      - name: 2. Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 3. Installer les dépendances
        run: |
          cd backend
          npm ci

      - name: 4. Lancer ESLint
        run: |
          cd backend
          npm run lint

      - name: 5. Lancer les tests
        run: |
          cd backend
          npm test -- --coverage

      - name: 6. Analyser avec SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: 7. Build et push image Docker backend
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u hub99-h --password-stdin
          docker build -t ghcr.io/hub99-h/tp-ci-backend:latest ./backend
          docker push ghcr.io/hub99-h/tp-ci-backend:latest